name: Deploy Infrastructure on Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-quality:
    name: Terraform quality code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2

      - name: Terraform Init
        id: init
        working-directory: terraform/environments/dev
        run: terraform init

      - name: Terraform Format Check
        id: fmt
        working-directory: terraform/environments/dev
        run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        working-directory: terraform/environments/dev
        run: terraform validate
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Terraform Plan
        id: plan
        working-directory: terraform/environments/dev
        run: terraform plan -input=false -var 'role_arn=arn:aws:iam::830543321077:role/LabRole'
  terraform-deploy:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2

      - name: Terraform Init
        id: init
        working-directory: terraform/environments/dev
        run: terraform init

      - name: Terraform Apply
        id: apply
        working-directory: terraform/environments/dev
        run: terraform apply -auto-approve -input=false -var 'role_arn=arn:aws:iam::830543321077:role/LabRole'
